Build not only x64
Icinga/docker-icingadb pull request #56
Opened 2023-01-17 10:17 UTC by Al2Klimov

2023-01-17 11:59 UTC, Al2Klimov commented
## TODO

* Icinga/docker-icinga2#73
* [ ] create all tags
* [ ] adjust GHA usage

2023-01-17 17:31 UTC, Al2Klimov commented
Test pipeline: https://github.com/Icinga/icingadb/actions/runs/3938296860/jobs/6744592491

2023-02-22 09:11 UTC, Al2Klimov commented
## TODO

* [ ] go mod dl only 1x

2023-05-23 10:45 UTC, Al2Klimov commented
> ## TODO
> * [ ]  go mod dl only 1x

Tbh. I already did literally the same here:

https://github.com/Icinga/docker-icinga2/blob/faecd36aa647f294a6a35114ee663889ba520ae7/Dockerfile#L14-L22

🤷‍♂️

2023-07-27 08:51 UTC, Al2Klimov commented
A clean Icinga DB v1.2.0 thing for me.

2023-08-04 08:37 UTC, Al2Klimov commented
@julianbrost I have to correct myself:

A clean Icinga DB ~v1.2.0~ v1.1.1 thing for me.

2023-08-07 10:49 UTC, julianbrost requested changes

2023-08-07 10:49 UTC, julianbrost commented on .github/workflows/build.yml
> +        run: sudo apt-get install -y qemu-user-static binfmt-support
Misses this change from https://github.com/Icinga/docker-icinga2/pull/99

2023-08-07 10:49 UTC, julianbrost commented on action.yml
> +      run: sudo apt-get install -y qemu-user-static binfmt-support
Misses this change from https://github.com/Icinga/docker-icinga2/pull/99

2023-08-07 10:49 UTC, julianbrost commented on platforms.txt
> +linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
It doesn't really make sense to build for more platforms than [we build Icinga 2 containers for](https://github.com/Icinga/docker-icinga2/blob/master/platforms.txt).

2023-08-07 10:51 UTC, julianbrost commented
> A clean Icinga DB ~v1.2.0~ v1.1.1 thing for me.

A clean "when there is time for it" thing. Like if it was very important, we could also upload new images for an existing release with additional architectures.

2023-08-07 14:04 UTC, julianbrost approved these changes

2023-08-07 14:04 UTC, merged

2023-08-07 14:49 UTC, dwt commented
🎉